# Generated by Django 4.2.2 on 2026-05-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newuser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuser",
            name="token",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Токен"
            ),
        ),
    ]
